### ISSUE TITLE
add topic interoperability

### ISSUE THREAD

**Issue by Beliavsky** [PDLPorters/extutils-f77#13]
I suggest adding the topic interoperability in the About section.

**Comment by mohawk2** [comment]
Thanks for the thought! I'm not a Fortran expert; are you referring to C <-> Fortran interoperability, or something else? Also, I'm not sure what you mean by the "About section", which isn't one of the sections of the POD documentation?

**Comment by zmughal** [comment]
I believe what @Beliavsky means is add it to the GitHub topics. Sure, I can do that.

**Comment by zmughal** [comment]
Done! Let me know if there is anything else.

**Comment by mohawk2** [comment]
That makes sense!

**Comment by mohawk2** [comment]
@Beliavsky This is a bit off-topic, sorry - feel free to ignore if you prefer. PDL supplies two Fortran libraries and builds them if a Fortran compiler is present (a major use for this module, in fact). In order to operate correctly on both 32- and 64-bit platforms, I updated the Slatec and Minuit libraries bundled in PDL. Is there any interest in me contributing those changes to an upstream copy of Slatec / Minuit, if such exists?

**Comment by d-lamb** [comment]
There is not a meaningful upstream for SLATEC.  Last release was in 1993, only two minor corrections since then, last in 1999.  I don't think it is currently maintained.  GSL was intended to be a replacement.  So I'm not sure there's any place to send those SLATEC changes.  Minuit seems to be similarly opaque, and largely replaced by an OO C++ interface Minuit2.

**Comment by mohawk2** [comment]
That would make sense! Perhaps PDL should have a Minuit2 interface. That does sort of suggest the Minuit interface in PDL could usefully (because of quicker builds and a slightly reduced maintenance burden) be removed?

**Comment by mohawk2** [comment]
@Beliavsky What do you think of the fortran-lang organisation hosting Slatec? Do you have comms with the netlib folks at all?

**Comment by zmughal** [comment]
I see a discussion of porting that functionality into stdlib here <https://github.com/fortran-lang/stdlib/issues/179>. But nothing about the whole SLATEC library being incorporated as far as I can tell. There has been some work on updating parts of SLATEC to F90 <https://people.math.sc.edu/Burkardt/f_src/slatec/slatec.html> and here is an update of one specifically on GitHub <https://github.com/fortran-lang/fftpack>.
